/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c7c4d7",
        "primary-container": "#6063ee",
        "secondary-container": "#9c48ea",
        "on-secondary-container": "#fffbff",
        "secondary-fixed-dim": "#ddb7ff",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#494bd6",
        "error": "#ba1a1a",
        "on-tertiary-container": "#f9fdff",
        "surface": "#f7f9fb",
        "on-surface-variant": "#464554",
        "surface-variant": "#e0e3e5",
        "inverse-primary": "#c0c1ff",
        "secondary": "#8127cf",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#767586",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "primary": "#4648d4",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "inverse-surface": "#2d3133",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        section_padding: "64px",
        stack_gap: "12px",
        gutter: "24px",
        max_width: "900px",
        card_padding: "20px",
      },
      fontFamily: {
        "label-caps": ["Space Grotesk", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "mono-script": ["Space Grotesk", "monospace"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "mono-script": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
